name: My CI on Hexlet

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup
        run: make setup
      
      - name: Linter
        run: make lint

      - name: Tests
        run: make test

